"""Non-secret default configuration values."""

MODELS_TO_RUN = ["google/gemma-4-26B-A4B-it", "google/diffusiongemma-26B-A4B-it"]
INFERENCE_MAX_BATCHES = 1

GEMMA_MODEL_NAME = "google/gemma-4-26B-A4B-it"
GEMMA_PROCESSOR_NAME = GEMMA_MODEL_NAME
GEMMA_MODEL_REVISION = "main"
GEMMA_MODEL_DTYPE = "bfloat16"
GEMMA_MODEL_DEVICE_MAP = "auto"

DIFFUSION_GEMMA_MODEL_NAME = "google/diffusiongemma-26B-A4B-it"
DIFFUSION_GEMMA_PROCESSOR_NAME = DIFFUSION_GEMMA_MODEL_NAME
DIFFUSION_GEMMA_MODEL_REVISION = "main"
DIFFUSION_GEMMA_MODEL_DTYPE = "bfloat16"
DIFFUSION_GEMMA_MODEL_DEVICE_MAP = "auto"

GEMMA_MAX_NEW_TOKENS = 256
GEMMA_ENABLE_THINKING = True
GEMMA_DO_SAMPLE = True
GEMMA_TEMPERATURE = 1.0
GEMMA_TOP_P = 0.95
GEMMA_TOP_K = 64

DIFFUSION_GEMMA_GEN_LENGTH = 256
DIFFUSION_GEMMA_MAX_DENOISING_STEPS = 48
DIFFUSION_GEMMA_T_MIN = 0.4
DIFFUSION_GEMMA_T_MAX = 0.8
DIFFUSION_GEMMA_ENTROPY_BOUND = 0.1
DIFFUSION_GEMMA_STABILITY_THRESHOLD = 1
DIFFUSION_GEMMA_CONFIDENCE_THRESHOLD = 0.005
# Applied only if the DiffusionGemma chat template supports it; ignored otherwise.
DIFFUSION_GEMMA_ENABLE_THINKING = True

# vLLM engine parameters (per kind; consumed by models/gemma_vllm.py and
# models/diffusion_gemma_vllm.py). USE_VLLM=False falls back to the in-process
# HuggingFace path in models/gemma.py / models/diffusion_gemma.py.
GEMMA_USE_VLLM = True
GEMMA_TENSOR_PARALLEL_SIZE = 1
GEMMA_MAX_NUM_SEQS = 256
GEMMA_GPU_MEMORY_UTILIZATION = 0.9
GEMMA_TRUST_REMOTE_CODE = False
GEMMA_MAX_MODEL_LEN = None

DIFFUSION_GEMMA_USE_VLLM = True
DIFFUSION_GEMMA_TENSOR_PARALLEL_SIZE = 1
# ponytail: diffusion keeps per-request canvas/history buffers on GPU, so vLLM's
# recipe caps concurrency low (~4). Raise only while watching for OOM.
DIFFUSION_GEMMA_MAX_NUM_SEQS = 4
DIFFUSION_GEMMA_GPU_MEMORY_UTILIZATION = 0.85
DIFFUSION_GEMMA_TRUST_REMOTE_CODE = False
DIFFUSION_GEMMA_MAX_MODEL_LEN = None

LOGGING_ROOT = "logging"
LOGGING_EXPERIMENT_ID = None
LOG_TOP_K = 5
LOG_MOE = False
LOG_TOKENS = False
LOG_LOGITS = False
LOG_CANVAS = False
LOG_SAVE_FULL_LOGITS = False
LOG_SEED = 42

DATASET_NAME = "tackhwa/multilingual_safety"
DATASET_REVISION = "main"
DATASET_SPLIT = "train"
DATASET_STREAMING = True
DATASET_MAX_SAMPLES = None
DATASET_LANGUAGES = []
DATASET_PROMPT_LABELS = []
DATASET_RESPONSE_LABELS = []
DATASET_TAGS = []
DATASET_SOURCES = []
DATASET_SEED = 42
DATASET_SHUFFLE = False
DATASET_SHUFFLE_BUFFER_SIZE = 10_000
DATASET_FILTER_NUM_PROC = None
DATASET_MAP_NUM_PROC = None
DATASET_NORMALIZE = True
HF_DATASETS_CACHE = None

BATCH_SIZE = 1
NUM_WORKERS = 0
PIN_MEMORY = False
