"""Non-secret default configuration values."""

MODELS_TO_RUN = ["gemma", "diffusion_gemma"]
INFERENCE_MAX_BATCHES = None

GEMMA_MODEL_NAME = "google/gemma-4-26B-A4B-it"
GEMMA_PROCESSOR_NAME = GEMMA_MODEL_NAME
GEMMA_MODEL_REVISION = "main"
GEMMA_MODEL_DTYPE = "bfloat16"
GEMMA_MODEL_DEVICE_MAP = "auto"

DIFFUSION_GEMMA_MODEL_NAME = "google/diffusiongemma-26B-A4B-it"
DIFFUSION_GEMMA_PROCESSOR_NAME = DIFFUSION_GEMMA_MODEL_NAME
DIFFUSION_GEMMA_MODEL_REVISION = "main"
DIFFUSION_GEMMA_MODEL_DTYPE = "bfloat16"
DIFFUSION_GEMMA_MODEL_DEVICE_MAP = "auto"

GEMMA_MAX_NEW_TOKENS = 2048
GEMMA_DO_SAMPLE = True
GEMMA_TEMPERATURE = 1.0
GEMMA_TOP_P = 0.95
GEMMA_TOP_K = 64

# Run both chat-template modes for every selected model.
THINKING_VARIANTS = ["non_thinking", "thinking"]

DIFFUSION_GEMMA_GEN_LENGTH = 2048
DIFFUSION_GEMMA_MAX_DENOISING_STEPS = 48
DIFFUSION_GEMMA_T_MIN = 0.4
DIFFUSION_GEMMA_T_MAX = 0.8
DIFFUSION_GEMMA_ENTROPY_BOUND = 0.1
DIFFUSION_GEMMA_STABILITY_THRESHOLD = 1
DIFFUSION_GEMMA_CONFIDENCE_THRESHOLD = 0.005

LOGGING_ROOT = "logging"
LOGGING_EXPERIMENT_ID = None
LOG_TOP_K = 5
LOG_MOE = False
LOG_LOGITS = False
LOG_SAVE_FULL_LOGITS = False
LOG_SEED = 42

DATASET_NAME = "tackhwa/multilingual_safety"
DATASET_REVISION = "main"
DATASET_SPLIT = "train"
DATASET_STREAMING = True
DATASET_MAX_SAMPLES = None
DATASET_LANGUAGES = []
DATASET_PROMPT_LABELS = []
DATASET_RESPONSE_LABELS = []
DATASET_TAGS = []
DATASET_SOURCES = []
DATASET_SEED = 42
DATASET_SHUFFLE = False
DATASET_SHUFFLE_BUFFER_SIZE = 10_000
DATASET_FILTER_NUM_PROC = None
DATASET_MAP_NUM_PROC = None
DATASET_NORMALIZE = True
HF_DATASETS_CACHE = None

BATCH_SIZE = 64
NUM_WORKERS = 0
PIN_MEMORY = False
